//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fortune_teller_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation
    {
        public int TransportationID { get; set; }
        public string TransportationMode { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
